apiVersion: v1
kind: Service
metadata:  
  name: client-svc
spec:
  selector:    
    app: client
  type: NodePort
  ports:  
  - name: client-svc
    port: 3000
    targetPort: 3000
    nodePort: 30057
    protocol: TCP
