apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server 
  template:
    metadata:
      labels:
        app: server 
    spec:
      containers:
      - name: server 
        image: monasamir/server:v${BUILD_NUMBER} 
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-uri
              key: MONGO_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jw
              key: JWT_SECRET

